service:
  name: scaleway-node10
configValidationMode: off
provider:
  name: scaleway
  runtime: node10
  # Global Environment variables - used in every functions
  env:
    test: test
  # the path to the credentials file needs to be absolute
  scwToken: <scw-token>
  scwOrganization: <scw-organization-id>

plugins:
  - serverless-scaleway-functions
  - serverless-offline-scaleway

package:
  exclude:
    - .gitignore
    - .git/**

functions:
  app:
    handler: handler.handler
    env:
      local: local